pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal() // Necesario para plugins externos como KSP
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()       // repositorio principal de Android
        mavenCentral() // librerías Kotlin, Room, etc.
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "Atrapame Si Puedes"
include ':app'
